name: Build assets

on:
  push:
    paths:
      - '.github/workflows/assets.yml'
      - 'public/**'
      - 'ui/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - '.github/workflows/assets.yml'
      - 'public/**'
      - 'ui/**'
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - 'pnpm-lock.yaml'

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: git submodule absorbgitdirs
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.14.2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: pnpm
      - uses: actions/checkout@v2
        with:
          repository: lichess-org/ab
          ssh-key: ${{ secrets.id_rsa_ab }}
          ref: master
          path: ab
        continue-on-error: true
        id: ab
      - run: pnpm link ./ab --dir ui/round
        if: steps.ab.outcome == 'success'
      - run: ./ui/build prod
      - run: mkdir assets && mv public assets/ && cp LICENSE COPYING.md README.md assets/ && git log -n 1 --pretty=oneline > assets/commit.txt
      - run: cd assets && tar -cvpJf ../assets.tar.xz . && cd -
        env:
          XZ_OPT: '-0'
      - uses: actions/upload-artifact@v1
        with:
          name: lila-assets
          path: assets.tar.xz
